-- CreateEnum
CREATE TYPE "OpponentPlayingStyleTag" AS ENUM ('HIGH_PRESSING', 'LOW_BLOCK', 'POSSESSION_BASED', 'DIRECT_PLAY', 'COUNTER_ATTACKING', 'PHYSICAL_AND_DIRECT', 'TECHNICAL_AND_PATIENT', 'FAST_PACED_TRANSITIONS', 'SLOW_BUILD_UP', 'DISCIPLINED_DEFENSIVE_SHAPE', 'MAN_TO_MAN_MARKING', 'ZONAL_PRESSING', 'MIXED_TRANSITIONS', 'SET_PIECE_ORIENTED', 'INDIVIDUAL_DRIBBLING', 'COMPACT_MIDFIELD', 'WIDE_PLAY_ORIENTED');

-- AlterTable
ALTER TABLE "OpponentEncounterObservation" ADD COLUMN "playingStyleTags" "OpponentPlayingStyleTag"[] DEFAULT ARRAY[]::"OpponentPlayingStyleTag"[];